const ProfileAvatarStore = [
    {
        id:"1",
        name:"Bear",
        imageDirectory:"/images/avatar/bear.png"
    },
    {
        id:"2",
        name:"Cat",
        imageDirectory:"/images/avatar/cat.png"
    },
    {
        id:"3",
        name:"Chicken",
        imageDirectory:"/images/avatar/chicken.png"
    },
    {
        id:"4",
        name:"Brutal Dog",
        imageDirectory:"/images/avatar/dog_brutal.png"
    },
    {
        id:"5",
        name:"Dog",
        imageDirectory:"/images/avatar/dog.png"
    },
    {
        id:"6",
        name:"Giraffe",
        imageDirectory:"/images/avatar/giraffe.png"
    },
    {
        id:"7",
        name:"Koala",
        imageDirectory:"/images/avatar/koala.png"
    },
    {
        id:"8",
        name:"Meerkat",
        imageDirectory:"/images/avatar/meerkat.png"
    },
    {
        id:"9",
        name:"Panda",
        imageDirectory:"/images/avatar/panda.png"
    },
    {
        id:"10",
        name:"Puffer Fish",
        imageDirectory:"/images/avatar/puffer-fish.png"
    },
    {
        id:"11",
        name:"Rabbit Clothes",
        imageDirectory:"/images/avatar/rabbit-clothes.png"
    },
    {
        id:"12",
        name:"Rabbit",
        imageDirectory:"/images/avatar/rabbit.png"
    },
    {
        id:"13",
        name:"Sea Lion",
        imageDirectory:"/images/avatar/sea-lion.png"
    },
    {
        id:"14",
        name:"Snake",
        imageDirectory:"/images/avatar/snake.png"
    },
    {
        id:"15",
        name:"Weasel",
        imageDirectory:"/images/avatar/weasel.png"
    },
]
export {ProfileAvatarStore};